name: Daily CFP Scraper

on:
  schedule:
    - cron: '0 8 * * *'  # Tous les jours à 8h UTC (10h en France métro)

jobs:
  scrape-cfp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run scraper
        run: |
          python agent_cfp.py

      - name: Commit and push updated CSV
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update CFP list - $(date)"
          file_pattern: "cfp_found.csv"